config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to: "tasks#show", as: :task
  post "/tasks", to: "tasks#create"
  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy", as: :delete_task
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end
  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end
  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to tasks_path, status: :see_other
  end
end

private

def task_params
  params.require(:task).permit(:title, :details, :completed)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit%>
<% end %>

<a href="<%= tasks_path %>">Back to list</a>

app/views/tasks/index.html.erb
<h1>My Task</h1>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <input type="checkbox" <%= 'checked' if task.completed %> />
      <strong><%= link_to task.title, task_path(task) %></strong>
      <span> | </span>
      <small><%= link_to "Supprimer", delete_task_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></small>
    </li>
  <% end %>
</ul>

<a href="<%= tasks_new_path %>">Add task</a>

app/views/tasks/new.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit%>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1> <a href="<%= edit_path %>">Edit task</a>
<div style="background-color: #f0f0f0; padding: 10px; border-radius: 5px; margin-top: 10px; width: 300px">
  <p><strong><%= @task.details %></strong></p>
  <p>
  </div>
    <input type="checkbox" <%= 'checked' if @task.completed %> disabled />
    <strong><%= @task.completed ? "La tâche est complétée ✅" : "La tâche n'est pas complétée ❌" %></strong>
  </p>

<a href="<%= tasks_path %>">Back to list</a>